name: Validate, Publish, and Map Latest Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  validate-and-publish:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version tag without 'v'
        id: extract_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Validate Docker build
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/simple_tcp_echo_service:test .
          docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/simple_tcp_echo_service:test --help || true

      - name: Build and push Docker image with version and latest tags
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/simple_tcp_echo_service:${{ env.TAG }}
            ${{ secrets.DOCKERHUB_USERNAME }}/simple_tcp_echo_service:latest

      - name: Confirm pushed images
        run: |
          echo "✅ Published ${{ secrets.DOCKERHUB_USERNAME }}/simple_tcp_echo_service:${{ env.TAG }}"
          echo "✅ Published ${{ secrets.DOCKERHUB_USERNAME }}/simple_tcp_echo_service:latest (mapped to ${{ env.TAG }})"
