name: Build, Test, and Publish to GHCR and Docker Hub

on:
  push:
    tags:
      - 'v*'

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Extract tag name
        id: extract_tag
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "TAG=${TAG}" >> $GITHUB_ENV

      - name: Build and push Docker image to GHCR and Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/ashishnaware/simple_tcp_echo_service:${{ env.TAG }}
            ghcr.io/ashishnaware/simple_tcp_echo_service:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/simple_tcp_echo_service:${{ env.TAG }}
            ${{ secrets.DOCKERHUB_USERNAME }}/simple_tcp_echo_service:latest

      - name: Test published GHCR image (version tag)
        run: |
          docker pull ghcr.io/ashishnaware/simple_tcp_echo_service:${{ env.TAG }}
          docker run --rm ghcr.io/ashishnaware/simple_tcp_echo_service:${{ env.TAG }} --help || true

      - name: Test published GHCR image (latest tag)
        run: |
          docker pull ghcr.io/ashishnaware/simple_tcp_echo_service:latest
          docker run --rm ghcr.io/ashishnaware/simple_tcp_echo_service:latest --help || true

      - name: Test published Docker Hub image (version tag)
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/simple_tcp_echo_service:${{ env.TAG }}
          docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/simple_tcp_echo_service:${{ env.TAG }} --help || true

      - name: Test published Docker Hub image (latest tag)
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/simple_tcp_echo_service:latest
          docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/simple_tcp_echo_service:latest --help || true

      - name: Confirm published images
        run: |
          echo "✅ Published and verified on GHCR: ghcr.io/ashishnaware/simple_tcp_echo_service:${{ env.TAG }} and :latest"
          echo "✅ Published and verified on Docker Hub: ${{ secrets.DOCKERHUB_USERNAME }}/simple_tcp_echo_service:${{ env.TAG }} and :latest"